### app.yaml

runtime: python312  
entrypoint: gunicorn -b :$PORT app:server

instance_class: F2 
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

readiness_check:
  app_start_timeout_sec: 600
