steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'us-central1-docker.pkg.dev/the-mesh-458219-a9/uranus-wyx/EmotionFlow/emotion_flow:$SHORT_SHA', 
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'us-central1-docker.pkg.dev/the-mesh-458219-a9/uranus-wyx/EmotionFlow/emotion_flow:$SHORT_SHA'
  ]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'emotion-flow-service', 
    '--image', 'us-central1-docker.pkg.dev/the-mesh-458219-a9/uranus-wyx/EmotionFlow/emotion_flow:$SHORT_SHA',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated'
  ]

images:
- 'us-central1-docker.pkg.dev/the-mesh-458219-a9/uranus-wyx/EmotionFlow/emotion_flow:$SHORT_SHA'
