options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1. 用 Dockerfile 构建镜像
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/emotionflow:$SHORT_SHA'
    - '.'

# 2. Push 镜像到 Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/emotionflow:$SHORT_SHA'

# 3. 部署到 Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'emotionflow'
    - '--image'
    - 'gcr.io/$PROJECT_ID/emotionflow:$SHORT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/emotionflow:$SHORT_SHA'
